/**
 * Builds a one-page PDF sale receipt and hands it to the device's share
 * sheet (Web Share API) when available, falling back to a direct download.
 */
(function () {
  function carLine(car) {
    if (!car) return 'Unknown vehicle';
    return `${car.year} ${car.make} ${car.model}`;
  }

  function buildReceiptDoc(sale, car) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF({ unit: 'pt', format: 'a4' });
    const marginX = 56;
    const rightEdge = 539;
    let y = 72;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);
    doc.text('Vehicle Sale Receipt', marginX, y);
    y += 10;
    doc.setDrawColor(210);
    y += 14;
    doc.line(marginX, y, rightEdge, y);
    y += 30;

    const section = (title) => {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(30);
      doc.text(title, marginX, y);
      y += 20;
    };

    const row = (label, value) => {
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(90);
      doc.text(label, marginX, y);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(20);
      doc.text(String(value === undefined || value === null || value === '' ? '—' : value), marginX + 160, y);
      y += 20;
    };

    section('Receipt');
    row('Receipt #', sale.id ? sale.id.slice(0, 8).toUpperCase() : '—');
    row('Sale Date', sale.saleDate || '—');
    y += 8;

    section('Vehicle');
    row('Vehicle', carLine(car));
    row('VIN', car && car.vin);
    row('Color', car && car.color);
    row('Mileage', car && car.mileage ? `${Number(car.mileage).toLocaleString()} mi` : null);
    y += 8;

    section('Buyer');
    row('Name', sale.buyerName);
    row('Contact', sale.buyerContact);
    y += 8;

    section('Payment');
    row('Sale Price', Helpers.formatCurrency(sale.salePrice));
    row('Status', sale.paymentStatus === 'paid' ? 'Paid' : 'Pending');

    if (sale.notes) {
      y += 8;
      section('Notes');
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(20);
      const lines = doc.splitTextToSize(sale.notes, rightEdge - marginX);
      doc.text(lines, marginX, y);
      y += lines.length * 15;
    }

    y += 24;
    doc.setDrawColor(210);
    doc.line(marginX, y, rightEdge, y);
    y += 20;
    doc.setFontSize(9);
    doc.setTextColor(140);
    doc.text('Generated by Car Trader Manager', marginX, y);

    return doc;
  }

  async function shareReceipt(sale, car) {
    const doc = buildReceiptDoc(sale, car);
    const fileName = `receipt-${(sale.id || 'sale').slice(0, 8)}.pdf`;
    const blob = doc.output('blob');

    if (navigator.share && navigator.canShare) {
      const file = new File([blob], fileName, { type: 'application/pdf' });
      if (navigator.canShare({ files: [file] })) {
        try {
          await navigator.share({
            files: [file],
            title: 'Sale Receipt',
            text: `Receipt for ${carLine(car)}`,
          });
          return { method: 'share' };
        } catch (err) {
          if (err && err.name === 'AbortError') return { method: 'cancelled' };
          // Fall through to download if sharing fails for any other reason.
        }
      }
    }

    doc.save(fileName);
    return { method: 'download' };
  }

  window.Receipt = { shareReceipt };
})();
